name: 🐍 Snake Game

on:
  schedule:
    # Executa a cada 5 horas
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Atualiza animação Snake
    runs-on: ubuntu-latest

    steps:
      # Clona o repositório
      - uses: actions/checkout@v3

      # Gera os arquivos da cobrinha
      - name: Gera SVG e GIF Snake
        uses: Platane/snk@v3
        with:
          github_user_name: klimadev
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake.gif?color_snake=#ff7e00&color_dots=#e6e6e6,#c0c0c0,#9e9e9e,#5c5c5c,#3c3c3c

      # Publica na branch output
      - name: Publica no GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
